### ISSUE TITLE
[Feature Request] SVG to SF Symbols

### ISSUE THREAD

**Issue by koolfreak** [rafaeltonholo/svg-to-compose#1]
Hi just tried s2c and it is awesome..is it possible you could write a converter similar to this but for iOS SF Symbol?

**Comment by rafaeltonholo** [comment]
Hi @koolfreak, I'm glad that you liked this repo!

Although having the same parse for SF Symbols would be very nice, I have no knowledge of the iOS ecosystem, thus I won't be able to help with that.

If the SF Symbols follow the same principle of creating an ImageVector in compose, it won't be too much trouble to implement it, but I would require some research to understand if that is feasible or not, and sadly I'm having limited time to work on this.

Also, if you already know how SF Symbols are built, feel free to contribute to this repo! I would be more than happy to help with it :)

**Comment by koolfreak** [comment]
Ok thanks....unfortunately i don't know also SF Symbols are built but they can be exported and modified in sketch
