### ISSUE TITLE
Fails silently when encountering files with spaces in them

### ISSUE THREAD

**Issue by ninovanhooff** [rafaeltonholo/svg-to-compose#2]
Thanks for this project, it's a great workflow optimization!

When processing a dir that contains svg names with spaces in them, the script will process files without spaces until it encounters the files with the space.
When closely inspecting the logs, you'll find out; but the script still completes successfully, even though it stopped processing with an error (remaining files without spaces are not processed)

```
./s2c.sh \
 -o ./ \
 -p your.app.package.icon \
 -t your.app.package.theme.YourAppComposeTheme \
 -cp YourAppIcons \
 ./Arrow\ Left.svg
 ```
 
 ```
 ./s2c.sh: line 1001: [: ./Arrow: binary operator expected
🔍 Directory detected
ls: ./Arrow: No such file or directory
ls: Left.svg: No such file or directory

🎉 SVG parsed to Jetpack Compose icon with success 🎉
```

Expected: either support files with spaces by sanitizing the name (just remove the whitespaces) or exit with an error status

**Comment by rafaeltonholo** [comment]
I have pushed a change to address that issue. Would you mind checking again if now it works? 
Thanks.
