### ISSUE TITLE
Reuse elements from defs

### ISSUE THREAD

**Issue by bartek-wesolowski** [rafaeltonholo/svg-to-compose#31]
I seems that currently elements declared in SVGs `<defs>` (e.g. those in `brasil.svg`) are inlined. The script could create a Composable function for each reusable element and call it with appropriate parameters instead of repeatedly creating the paths. It would reduce the generated Composable function size and complexity.

**Comment by rafaeltonholo** [comment]
Hi @bartek-wesolowski, thanks for bringing this up!

The current version of the CLI does not support using the `<defs>` tag, however, there's a WIP feature (https://github.com/rafaeltonholo/svg-to-compose/pull/32) that I'm adding to support it.

Your point is correct. SVG uses the nodes declared within the `<defs>` to create reusable nodes where you can reference them using the `<use>` tag.

However, there are a few points I need to emphasize:

Regarding creating `Composable` functions for the elements inside `<defs>`: one of the ideas of creating an `ImageVector` is to allow the usage of the icon wherever part of the code we want, so creating a `Composable` function is not an option here. It's also important to note that the `ImageVector.Builder` does not have a composable context, so we can't call composable functions here. 

However, that doesn't mean we can't call other methods, which leads to my second point.

When I started adding support for the `<use>` tags in this WIP feature (https://github.com/rafaeltonholo/svg-to-compose/pull/32), I started with the feeling that I could create small functions that would compose the icon creation and could be called when the `<use>` tag is used.

Using the `brasil.svg` file as an example, the initial idea would lead to an icon like this:
```kotlin
val Brasil: ImageVector
    get() {
        val current = _brasil
        if (current != null) return current

        return ImageVector.Builder(/* params */).apply {
            // a bunch of other path instructions
            // <use xlink:href="#o" x="-600" y="-132"/>
            useO()
        }.build().also { _brasil = it }
    }

private fun ImageVector.Builder.useO() {
    // <use xlink:href="#f" id="o" transform="scale(31.5)"/>
    useF()
}

private fun ImageVector.Builder.useF() {
    // <g id="f" fill="#fff">
    //     <g id="e">
    //         <path id="d" d="M0-1v1h.5" transform="rotate(18 0 -1)"/>
    //         <use xlink:href="#d" transform="scale(-1 1)"/>
    //     </g>
    //     <use xlink:href="#e" transform="rotate(72)"/>
    //     <use xlink:href="#e" transform="rotate(-72)"/>
    //     <use xlink:href="#e" transform="rotate(144)"/>
    //     <use xlink:href="#e" transform="rotate(-144)"/>
    // </g>
    group {
        group { /* draw instructions */ }
        // other use fn calls
    }
}
```

However, there is a problem with this approach. According to the SVG definition, whenever we use the `<use>` tag, behind the scenes the renderer creates a group with some transformations, depending on what attribute the tag has, and it can also accept other transformations, as we can see in the mentioned icon.

The main problem is that these transformations can even change the behaviour of a drawing command, for example, it can turn a `horizontalLineTo` into a `lineTo`.

It is important to mention that these transformations involve geometric calculations that can be quite expensive in terms of computation, and I think that is why Google performs these calculations when transforming SVGs to AVGs via Android Studio. Avgs doesn't support such transformations on paths, only on groups, unlike Svgs.

After analyzing this, I came to the understanding that the end result for each `<use>` element could lead to a completely different result, creating a huge barrier in terms of generating reusable methods for it.

I wouldn't say it's impossible, but it would require a deeper investigation to understand if it would be possible without ending up with a function with 20+ arguments, depending on how big the reusable element definition is inside the `<defs>` tag.
