### ISSUE TITLE
Relative coordinates with negative initial bounds

### ISSUE THREAD

**Issue by andreydang** [rafaeltonholo/svg-to-compose#63]
Hi, I'm using your great library and I've encountered a rendering problem. I tried to convert this image as an example: 

https://upload.wikimedia.org/wikipedia/commons/d/d7/Android_robot.svg

With initial negative borders, no shift occurs

viewBox="-147 -70 294 345"

```
                moveToRelative(dx = -95.0f, dy = 44.5f)
                lineToRelative(dx = 190.0f, dy = 0.0f)
```
![pic](https://github.com/user-attachments/assets/dba7f6e9-6f2f-4421-90c0-0cd6d6cc6be7)

```
                moveToRelative(52.0f, 114.5f)
                lineToRelative(190.0f,0f)
```
![pic2](https://github.com/user-attachments/assets/6fdd605b-b62b-4a88-aa53-979ae18469d7)

It looks like when the element is positioned relative, it does not add the initial border offset.

```
 -95.0+147 = 52
  44.5+70 = 114.5
```

I believe that somewhere the shift is not taken into account, but 0 is set. In editors and in the browser, the SVG is displayed correctly.

**Comment by rafaeltonholo** [comment]
Hi @andreydang,

Thank you for reporting the bug! I have identified the issue, and a fix will be in place soon. Additionally, I have identified another issue related to round rectangles not considering floating point values, which has also been addressed. You should see your icon correctly rendered in the new release.

Thank you for using this CLI :)

**Comment by andreydang** [comment]
Hi @rafaeltonholo 
Thank you very much! Awesome)
